# Generated by Django 5.2 on 2025-05-08 10:01

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Nigerian phone number (e.g., 08012345678 or +2348012345678)', max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(11, message='Phone Number must be at least 11 characters long.'), authentication.models.validate_nigerian_phone]),
        ),
    ]
